accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view,name='signup'),
    url(r'^login/$', views.login_view,name='login'),
    url(r'^logout/$', views.logout_view,name='logout')
]

articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'
urlpatterns = [
    url(r'^$', views.articles, name='list'),
    url(r'^create/', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

maua/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as articles_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^about$', views.about),
    url(r'^$', articles_view.articles, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg', blank=True)

    def __str__(self): #defines how the articles are going to look like both in the shell and the admin,,human-readable
        return self.title

    def snippet(self):
        return self.body[:400] + '...'

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.EmailField(max_length=20,
                            widget=forms.TextInput(attrs={'class' :'form-control', 'placeholder' : 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
								attrs={'class' :'form-control', 'placeholder' : 'password'}))


class SignupForm(forms.Form):
    username = forms.EmailField(max_length=20,
                            widget=forms.TextInput(attrs={'class' :'form-control', 'placeholder' : 'username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
								attrs={'class' :'form-control', 'placeholder' : 'password'}))

    password2 = forms.CharField( widget=forms.PasswordInput(
                                 attrs={'class': 'form-control', 'placeholder': 'r_password'} ) )

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from .forms import LoginForm,SignupForm

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = SignupForm
    return render(request,'accounts/sign_ju.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = LoginForm
    return render(request,'accounts/sign.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render
from .models import Article
from django.contrib.auth.decorators import login_required

def articles(request):
    articles = Article.objects.all().order_by('-date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url='accounts:login')
def article_create(request):
    return render(request,'articles/article_create.html')

maua/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

def home(request):
    return render(request, 'home.html')

accounts/templates/accounts/login.html
{% extends 'base_lay.html' %}
{% block content %}

    <h3>Login</h3>

    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/sign.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SignIn</title>

    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'login.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">sign in</h2>

        {{ form.username }}

        {{ form.password }}

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}

        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->
  </body>
</html>

accounts/templates/accounts/sign_ju.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SignUp</title>

    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'login.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Sign Up</h2>

        {{ form.username }}

        {{ form.password1 }}

        {{ form.password2 }}

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}

        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
      </form>

    </div> <!-- /container -->
  </body>
</html>

accounts/templates/accounts/signup.html
{% extends 'base_lay.html' %}
{% block content %}

    <h3>Sign Up</h3>

    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="SignUp">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_lay.html' %}
{% block content %}

    <div class="container">
        <h3> Got something to bitch about? </h3>
    </div>

 {% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_lay.html' %}
{% block content %}
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}">
            <h3>{{ article.title }}</h3>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
            <p class="author"> Written by: {{ article.author.username }} </p>
        </div>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_lay.html' %}
{% block content %}

    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h3><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h3>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
            </div>
        {% endfor %}
    </div>

 {% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
</head>
<body>
    <h3>Abot Piage</h3>
    <p>This is the about shiut</p>
</body>
</html>

templates/base_lay.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <h3><a href="{% url 'home' %}"><img src="{% static 'log.png' %}" alt="jango" /></a></h3>

        <nav>
            <ul>

                    {% if user.is_authenticated %}

                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                       <li><button type="submit">Logout</button></li>
                    </form>

                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                     {% endif %}


            </ul>
        </nav>
      </header>

      <div class="wrapper">
        {% block content %}
        {% endblock %}
      </div>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h3>Hoe Piage</h3>
    <p>This is the home shiut</p>
</body>
</html>